"""empty message

Revision ID: 94d0a9a078e2
Revises: 9ef44b7fda71
Create Date: 2023-08-25 16:00:16.190953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d0a9a078e2'
down_revision = '9ef44b7fda71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('hour_block', sa.String(length=120), nullable=False))

    with op.batch_alter_table('sport_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=24), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_center', schema=None) as batch_op:
        batch_op.drop_column('url_img')

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.drop_column('hour_block')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
