"""empty message

<<<<<<<< HEAD:migrations/versions/04fc0f07090f_.py
Revision ID: 04fc0f07090f
Revises: 
Create Date: 2023-08-31 00:06:17.912969
========
Revision ID: 977b7c5140e8
Revises: 
Create Date: 2023-08-30 23:30:13.575033
>>>>>>>> 6d91176d157e6fbf3615e6b316a15677e3dacb70:migrations/versions/977b7c5140e8_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/04fc0f07090f_.py
revision = '04fc0f07090f'
========
revision = '977b7c5140e8'
>>>>>>>> 6d91176d157e6fbf3615e6b316a15677e3dacb70:migrations/versions/977b7c5140e8_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('salt'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('sport_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=800), nullable=False),
    sa.Column('phone_number', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url_img', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sport', sa.String(length=120), nullable=False),
    sa.Column('sport_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_center_id'], ['sport_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court_schedule')
    op.drop_table('court')
    op.drop_table('sport_center')
    op.drop_table('user')
    op.drop_table('contact')
    # ### end Alembic commands ###
