"""empty message

Revision ID: f19a737b0722
Revises: 6a28efcd47e0
Create Date: 2023-08-23 22:48:40.606885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19a737b0722'
down_revision = '6a28efcd47e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('center_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_center_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('center_schedule_center_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sport_center', ['sport_center_id'], ['id'])
        batch_op.drop_column('center_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('center_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('center_schedule_center_id_fkey', 'sport_center', ['center_id'], ['id'])
        batch_op.drop_column('sport_center_id')

    # ### end Alembic commands ###
